@JobAddress = https://localhost:44354

GET {{JobAddress}}/api/job/
Accept: application/json

###

POST {{JobAddress}}/api/job/
Content-Type: application/json

{
    "title" : "Angular Developer",
    "description" : "Ontwikkelt in de taal Angular",
    "companyid" : 1
}

###

GET {{JobAddress}}/api/company/
Accept: application/json

###

POST {{JobAddress}}/api/company/
Content-Type: application/json

{
    "name" : "Dummy",
    "address" : "Dummystad" 
}

###

GET {{JobAddress}}/api/company/companieswithjobs
Accept: application/json
